### ISSUE TITLE
Blinky code does not run after power reset

### ISSUE THREAD

**Issue by chrismolli** [rust-embedded/msp430-quickstart#5]
Hey guys,

I am creating a version of the blinky example for my MSP430FR6972. The code compiles and also executes after flashing it to the MCU using the BSL interface. However **upon resetting the power of the MCU the blinky code does not run again**, even when I try setting the program counter back to the start of ROM (0x004000).

For comparison I compiled the blinky example provided by Texas Instruments (C Code). It runs blinking my debug led. Furthermore, it restarts and runs successfully even after power reset.

Not sure were to look for trouble shooting so I thought maybe you could give me a hint. My blinky rust code is available [here](https://github.com/chrismolli/msp430fr6972_blinky).

My workflow is the following
- Create ELF binary using msp430-elf-gcc compiler
- Use objcopy to flatten the ELF to a raw binary
- Use the BSL to write the 48218 bytes to the ROM starting at 0x004000

To compare the to binaries I attached both the disassembly of the working C-Code example and my partially working Rust Blinky code. However, I cannot figure out why it is not able to properly reset upon power cycling. Seems like the official blinky code is starting at 0x004002.

[c_code_disassembly.txt](https://github.com/rust-embedded/msp430-quickstart/files/6409427/c_code_disassembly.txt)
[rust_code_disassembly.txt](https://github.com/rust-embedded/msp430-quickstart/files/6409428/rust_code_disassembly.txt)

**Comment by chrismolli** [comment]
Okay I found the issue. The MCU contains a internal brown out protection that sets all outgoing pins to high-impedance by default. This must be cleared after reset from brownout (i.e. me pulling the plug) by clearing the PM5CTL0 register within the beginning of the main.

``` rust
p.PMM.pm5ctl0.modify(|_,w| {unsafe {w.bits(0x00)}});
```

**Comment by cr1901** [comment]
Hmm, I've never seen this before. The examples are tailored for msp430g2553, but I do include comments that apply to other variants. I think perhaps we should add some commented out code mentioning your code above in the `blinky` example (and other relevant examples)?

Also, I'm impressed a completely unoptimized Rust binary fits onto msp430 at all :D!

**Comment by chrismolli** [comment]
Oh quite the contrary. Its actually using maximum optimisation. I build the executable using
```
[profile.release]
opt-level = "s" 
codegen-units = 1
lto = "fat" 
```
I only inflate the binary to write it using my self-made BSL implementation. Since I didn't want to buy any additional hardware after it turned out that my Blackmagic probe could not program the MSP430 series.

Actually this brown-out locking seems quite useful to avoid drawing current from the GPIOs.

**Comment by kellda** [comment]
> The MCU contains a internal brown out protection that sets all outgoing pins to high-impedance by default. This must be cleared after reset from brownout (i.e. me pulling the plug) by clearing the PM5CTL0 register within the beginning of the main.

Yes this has to be done for all FRAM based devices (msp430fr* I think). The reason is that (because of the memory technology used) the initial value of I/O registers is not defined, so you have to explicitly enable I/O once it's configured.

**Comment by cr1901** [comment]
Thanks for that info! Is the register that must be cleared the same across FRAM devices?

My current plan is to put a comment in the examples indicating this line _or similar_ is required for FRAM devices: `p.PMM.pm5ctl0.modify(|_,w| {unsafe {w.bits(0x00)}});`.

Unfortunately, with the provided DSLite files (from which SVDs are generated), I've found the naming of actual registers (or fields, in the case of `PORT_1_2` peripheral) inconsistent between msp430 devices. `PMM` seems fine as a peripheral name, but I wonder if `pm5ctl0` is a device-specific register name?

**Comment by chrismolli** [comment]
The PM5CTL0 is the control register for the `Power Mode 5`, which is common to all MSP430FR58xx, MSP430FR59xx and MSP430FR6xx device families. It is part of the Power Management Module `PMM`. (See TI Document SLAU367P for more information)
